apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: node-auth-service
  namespace: auth-service
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 180
  selector:
    matchLabels:
      app: node-auth-service
  template:
    metadata:
      labels:
        app: node-auth-service
    spec:
      containers:
        - name: node-auth-service
          image: localdemoacr.azurecr.io/vaibhavauthservice
          ports:
            - containerPort: 5001
---
apiVersion: v1
kind: Service
metadata:
  name: node-auth-service
  namespace: auth-service
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 5001
      protocol: TCP
      targetPort: 5001
  selector:
    app: node-auth-service
