apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  spec:
    replicas: 1
    template:
      metadata:
        labels:
          app: nodejs
      spec:
        containers:
          - name: localdemoacr
            image: vaibhavauthservice
            ports:
              - containerPort: 3000
